#!/bin/bash
set -o pipefail

do_install() {

  date

  . helpers/install-functions.sh
  . gestalt.conf

  configfile=$1
  if [ -z "$configfile" ]; then
    exit_with_error "Must specify a configuration file"
  fi

  if [ ! -f "$configfile" ]; then
    exit_with_error "Configuration file '$configfile' not found, aborting."
  fi

  echo "Checking for required dependencies..."

  # mkdir -p ./tmp
  # exit_on_error "Could not create './tmp', aborting. Check filesystem permissions and try again."

  check_for_required_tools

  # Include configuration
  . $configfile

  install_prefix=${install_prefix-gestalt}
  install_namespace="${install_prefix}-system"

  # Environment checks
  check_kubeconfig
  check_for_kube
  check_cluster_capacity
  check_for_helm
  create_or_check_for_required_namespace
  check_for_prior_install

  download_fog_cli

  # Build Helm config
  . helpers/build-gestalt-config.sh
  process_kubeconfig
  # prompt_for_executor_config
  build_cli_config
  generate_gestalt_config > gestalt-config.yaml
  echo "Helm chart configuration generated."

  # Prompt to continue
  summarize_config
  prompt_or_wait_to_continue

  run_pre_install

  # Perform Gestalt installation
  # create_namespace
  run_helm_install          gestalt-config.yaml
  run_post_deploy

  wait_for_install_completion

  cleanup

  run_post_install

  . helpers/setup-sample-resources

  display_summary
}

if [ "$1" != "do_install" ]; then 
  mkdir -p ./logs
  ./install-gestalt-platform do_install $@ 2>&1 | tee -a ./logs/install.log
else
  shift
  do_install $@
fi
