#!/bin/bash

. helpers/install-functions.sh

prompt_to_continue(){
  echo ""
  echo "Gestalt Platform will be removed from Kubernetes cluster '`kubectl config current-context`'." # " and namespace '$install_namespace' will be deleted."
  echo "This cannot be undone."
  echo ""

  while true; do
      read -p "$* Proceed? [y/n]: " yn
      case $yn in
          [Yy]*) return 0  ;;
          [Nn]*) echo "Aborted" ; exit  1 ;;
      esac
  done
}

remove_gestalt_platform() {
  if [ -f ./helm ]; then
    helm=./helm
  else
    helm=helm
  fi

  name=$install_prefix
  $helm status $name >/dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Nothing to do - Helm deployment '$name' not found."
  else
    echo "OK - Helm deployment '$name' found."

    echo "Removing Helm deployment '$install_prefix' ..."

    $helm delete --purge $install_prefix
  fi

  kubectl get namespace $install_namespace > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Nothing to do - Kubernetes namespace '$install_namespace' isn't present."
  # else
    # echo "Deleting namespace '$install_namespace'..."
    # kubectl delete namespace $install_namespace
  fi
}

remove_gestalt_namespaces() {
  local namespaces=$( kubectl get namespaces | grep -E '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}' | awk '{print $1}')
  if [ $? -eq 0 ] && [ ! -z "$namespaces" ]; then
    echo ""
    echo "Warning: There are existing namespaces that appear to be from a prior install:"
    echo "$namespaces"
    echo ""

    while true; do
        read -p "$* Delete these namespaces? [y/n]: " yn
        case $yn in
            [Yy]*) do_delete_namespaces $namespaces ; break ;;
            [Nn]*) break ;;
        esac
    done
  else
    echo "No gestalt namespaces found"
  fi
}

do_delete_namespaces() {
  kubectl delete namespace $@
  echo "Done deleting namespaces."
}

install_prefix=$1
install_namespace=$2

if [ -z "$install_prefix" ]; then
  # exit_with_error "Must specify install_prefix"
  install_prefix=gestalt
fi

if [ -z "$install_namespace" ]; then
  install_namespace=${install_prefix}-system
fi


# Check for pre-reqs
check_for_required_tools
check_for_kube
check_for_helm_no_download

# Sanity check that gestalt-platform exists
# check_for_gestalt

prompt_to_continue

remove_gestalt_platform

remove_gestalt_namespaces

echo "Done."
