#!/bin/bash
#
# Removes Gestalt Platform components from the Kubernetes cluster in the current kubectl context
#
# First deletes Gestalt components from the 'gestalt-system' namespace, then prompts user to 
# delete namespaces in UUID format, assuming those namespaces were created as part of the
# Gestalt Platform installation.

. helpers/install-functions.sh

prompt_to_continue(){
  echo ""
  echo "Gestalt Platform will be removed from Kubernetes cluster '`kubectl config current-context`'."
  echo "This cannot be undone."
  echo ""

  while true; do
      read -p "$* Proceed? [y/n]: " yn
      case $yn in
          [Yy]*) return 0  ;;
          [Nn]*) echo "Aborted" ; exit  1 ;;
      esac
  done
}

remove_gestalt_platform() {

  # First, check if the namespace is even present

  kubectl get namespace $install_namespace > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Nothing to do - Kubernetes namespace '$install_namespace' isn't present."
    return 0
  fi

  # Remove Gestalt Platform

  echo ""
  echo "Removing Gestalt Platform components from '$install_namespace' namespace..."
  kubectl delete daemonsets,replicasets,statefulsets,services,deployments,pods,rc,secrets,configmaps,pvc,ingresses \
    --timeout=30s --all --namespace $install_namespace

  if [ $? -ne 0 ]; then
  
    # Removal was unsuccessful, try force removal

    echo ""
    echo "Warning: 'kubectl delete' failed, re-attempting with forceful delete..."
    echo ""
    
    # The --force flag helps clean up pods stuck in the 'Terminating' state
    kubectl delete daemonsets,replicasets,statefulsets,services,deployments,pods,rc,secrets,configmaps,pvc,ingresses \
      --grace-period=0 --force --all --namespace $install_namespace
  fi
}

remove_gestalt_namespaces() {
  local namespaces=$( kubectl get namespaces | grep -E '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}' | awk '{print $1}')
  if [ $? -eq 0 ] && [ ! -z "$namespaces" ]; then
    echo ""
    echo "Warning: There are existing namespaces that appear to be from a prior install:"
    echo "$namespaces"
    echo ""

    while true; do
        read -p "$* Delete these namespaces? [y/n]: " yn
        case $yn in
            [Yy]*) do_delete_namespaces $namespaces ; break ;;
            [Nn]*) break ;;
        esac
    done
  else
    echo "No gestalt namespaces found"
  fi
}

do_delete_namespaces() {
  kubectl delete namespace $@
  echo "Done deleting namespaces."
}

install_prefix=$1
install_namespace=$2

if [ -z "$install_prefix" ]; then
  install_prefix=gestalt
fi

if [ -z "$install_namespace" ]; then
  install_namespace=${install_prefix}-system
fi


# Check for pre-reqs
check_for_required_tools
check_for_kube

prompt_to_continue

remove_gestalt_platform

remove_gestalt_namespaces

echo "Done."
