#!/bin/bash

. helpers/install-functions.sh

check_for_gestalt() {
  echo "Checking for existing Gestalt Platform..."

  name=$INSTALL_PREFIX

  helm status $name >/dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Nothing to do - Helm deployment '$name' not found."
    exit 1
  fi
  echo "OK - Helm deployment '$name' found."

  kubectl get namespace $INSTALL_NAMESPACE > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Nothing to do - Kubernetes namespace '$INSTALL_NAMESPACE' isn't present."
    exit 1
  fi
  echo "OK - Kubernetes namespace '$INSTALL_NAMESPACE' found."
}

prompt_to_continue(){
  echo ""
  echo "Gestalt Platform will be removed from Kubernetes cluster '`kubectl config current-context`' and namespace '$INSTALL_NAMESPACE' will be deleted."
  echo "This cannot be undone."
  echo ""

  while true; do
      read -p "$* Proceed? [y/n]: " yn
      case $yn in
          [Yy]*) return 0  ;;
          [Nn]*) echo "Aborted" ; exit  1 ;;
      esac
  done
}

remove_gestalt_platform() {
  echo "Removing Helm deployment '$INSTALL_PREFIX' ..."
  helm delete --purge $INSTALL_PREFIX

  echo "Deleting namespace '$INSTALL_NAMESPACE'..."
  kubectl delete namespace $INSTALL_NAMESPACE
}

remove_gestalt_namespaces() {

  local namespaces=$( kubectl get namespaces | grep -E '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}' | awk '{print $1}')
  if [ $? -eq 0 ] && [ ! -z "$namespaces" ]; then
    echo ""
    echo "Warning: There are existing namespaces that appear to be from a prior install:"
    echo "$namespaces"
    echo ""

    while true; do
        read -p "$* Delete these namespaces? [y/n]: " yn
        case $yn in
            [Yy]*) do_delete_namespaces $namespaces ; break ;;
            [Nn]*) break ;;
        esac
    done
  else
    echo "No gestalt namespaces found"
  fi
}

do_delete_namespaces() {
  kubectl delete namespace $@
  echo "Done deleting namespaces."
}

INSTALL_PREFIX=$1
INSTALL_NAMESPACE=$2

if [ -z "$INSTALL_PREFIX" ]; then
  # exit_with_error "Must specify INSTALL_PREFIX"
  INSTALL_PREFIX=gestalt
fi

if [ -z "$INSTALL_NAMESPACE" ]; then
  INSTALL_NAMESPACE=${INSTALL_PREFIX}-system
fi


# Check for pre-reqs
check_for_required_tools
check_for_kube
check_for_helm

# Sanity check that gestalt-platform exists
check_for_gestalt

prompt_to_continue

remove_gestalt_platform

remove_gestalt_namespaces

echo "Done."
