#!/bin/bash

run() {
  local cmd="$@"
  echo
  echo ========================================================================================================================
  echo $cmd
  echo ========================================================================================================================
  echo
  $cmd 2>&1
  echo
}

run_diagnostics() {
  run uname -a
  
  run kubectl version

  run kubectl cluster-info

  run kubectl config current-context

  run kubectl config get-contexts

  run kubectl get deploy --all-namespaces

  run kubectl get pods --all-namespaces

  run kubectl get pvc --all-namespaces

  run kubectl get svc --all-namespaces

  run kubectl get all --all-namespaces

  run kubectl top pod --all-namespaces

  run kubectl describe nodes

  run ./helpers/check-cluster-capacity

  helm=helm
  which helm
  if [ $? -ne 0 ]; then
    helm=./helm
  fi

  run $helm version --tiller-connection-timeout 10

  run ./fog --version

  run ./fog status

  echo
}

capture_log() {
  if [ ! -f $1 ]; then 
    echo "$1 doesn't exist"
    return 0
  fi
  cat - <<EOF
========================================================================================================================
cat $1
========================================================================================================================
`cat $1`

EOF
}

if [ -z "$1" ]; then 
  mkdir -p logs

  date > ./logs/diagnostics.log

  ./run-diagnostics run_diagnostics | tee -a ./logs/diagnostics.log

  capture_log ./logs/install.log >> ./logs/diagnostics.log

  capture_log ./logs/gestalt-installer.log >> ./logs/diagnostics.log

  echo "Diagnostic info written to './logs/diagnostics.log'." | tee -a ./logs/diagnostics.log
elif [ "$1" == "run_diagnostics" ]; then
  run_diagnostics
else
  echo "Usage: ./run_diagnostics"
fi