#!/bin/bash

run() {
  local cmd="$@"
  echo
  echo ========================================================================================================================
  echo $cmd
  echo ========================================================================================================================
  echo
  $cmd 2>&1
  echo
}

run_diagnostics() {
  run uname -a
  
  run kubectl version

  run kubectl cluster-info

  run kubectl config current-context

  run kubectl config get-contexts

  run kubectl get deploy --all-namespaces

  run kubectl get pods --all-namespaces

  run kubectl get pvc --all-namespaces

  run kubectl get svc --all-namespaces

  run kubectl get all --all-namespaces

  run kubectl top pod --all-namespaces

  run kubectl describe nodes

  run ./helpers/check-cluster-capacity

  helm=helm
  which helm
  if [ $? -ne 0 ]; then
    helm=./helm
  fi

  run $helm version --tiller-connection-timeout 10

  run ./fog --version

  run ./fog status

  echo
}

if [ -z "$1" ]; then 
  mkdir -p diagnostics
  rm -r ./diagnostics/*
  date > ./diagnostics/diagnostics.log
  ./run-diagnostics run_diagnostics | tee -a ./diagnostics/diagnostics.log
  echo "------------------------------------gestalt-installer.log------------------------------------" >> ./diagnostics/diagnostics.log
  cat ./gestalt-installer.log >> ./diagnostics/diagnostics.log
  echo "Diagnostic info written to './diagnostics/diagnostics.log'."
else
  run_diagnostics
fi