#!/bin/bash

run() {
  local cmd="$@"
  echo
  echo ========================================================================================================================
  echo $cmd
  echo ========================================================================================================================
  echo
  $cmd
  echo
}

run_diagnostics() {
  run kubectl version

  run kubectl cluster-info

  run kubectl get pods --all-namespaces

  run kubectl top pod --all-namespaces

  run kubectl describe nodes

  run ./helpers/check-cluster-capacity

  helm=helm
  which helm
  if [ $? -ne 0 ]; then
    helm=./helm
  fi

  run $helm version --tiller-connection-timeout 10

  run ./fog --version

  run ./fog status

  echo "Diagnostic info written to './diagnostics/diagnostics.log'."
}

if [ -z "$1" ]; then 
  mkdir -p diagnostics
  rm -r ./diagnostics/*
  date > ./diagnostics/diagnostics.log
  ./run-diagnostics run_diagnostics | tee -a ./diagnostics/diagnostics.log
  cp *.log diagnostics/
else
  run_diagnostics
fi