apiVersion: v1
kind: Service
metadata:
  name: gestalt-elastic
  labels:
    gestalt-app: elastic
spec:
  selector:
    gestalt-app: elastic
  ports:
    - name: service-api
      port: {{.Values.elastic.restPort}}
      targetPort: rest
    - name: http-api
      port: {{.Values.elastic.transportPort}}
      targetPort: transport
