apiVersion: v1
kind: Secret
metadata:
  name: gestalt-secrets
type: Opaque
data:
  db-username: "{{ .Values.DB.Username | b64enc }}"
  db-password: "{{ .Values.DB.Password | b64enc }}"
  admin-username: "{{ .Values.Security.AdminUser | b64enc }}"
  admin-password: "{{ .Values.Security.AdminPassword | b64enc }}"
