# This is a pod w/ restartPolicy=Never so that the installer only runs once.
apiVersion: v1
kind: Pod
metadata:
  name: gestalt-installer
  labels:
    gestalt-app: installer
spec:
  restartPolicy: Never
  containers:
  - name: gestalt-installer
    image: "{{ .Values.installer.image }}"
    imagePullPolicy: Always
    # imagePullPolicy: {{ .Values.common.imagePullPolicy }}
    # 'deploy' arg signals deployment of gestalt platform
    # 'debug' arg signals debug output
    args: ["install", "{{ .Values.installer.mode }}"]
    env:

    # General settings
    # TODO: Not used
    # - name: ENSEMBLE_RELEASE_TAG
    #   value: "{{ .Values.common.releaseTag }}"
    - name: USE_DYNAMIC_LOADBALANCERS
      value: "{{ .Values.installer.useDynamicLoadBalancers }}"
    - name: EXTERNAL_GATEWAY_HOST
      value: "{{ .Values.installer.externalGateway.dnsName }}"
    - name: EXTERNAL_GATEWAY_PROTOCOL
      value: "{{ .Values.installer.externalGateway.protocol }}"
    - name: KONG_INGRESS_SERVICE_NAME
      value: "{{ .Values.installer.externalGateway.kongServiceName }}"
      #TODO
    - name: KONG_SERVICE_NODEPORT
      value: "{{ .Values.kong.nodePort }}"

    # Database settings
    - name: DATABASE_HOSTNAME
      value: "{{ .Values.db.hostname }}"
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gestalt-secrets
          key: db-password
    - name: DATABASE_PORT
      value: "{{ .Values.db.port }}"
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: gestalt-secrets
          key: db-username
    - name: DATABASE_NAME
      value: "{{ .Values.db.databaseName }}"

    # Security settings
    - name: SECURITY_DB_NAME
      value: "{{ .Values.security.databaseName }}"
    - name: SECURITY_HOSTNAME
      value: "{{ .Values.security.hostname }}"
    - name: SECURITY_PORT
      value: "{{ .Values.security.port }}"
    - name: SECURITY_PROTOCOL
      value: "{{ .Values.security.protocol }}"
    - name: SECURITY_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: gestalt-secrets
          key: admin-username
    - name: SECURITY_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gestalt-secrets
          key: admin-password

    # Meta settings
    - name: META_HOSTNAME
      value: "{{ .Values.meta.hostname }}"
    - name: META_PORT
      value: "{{ .Values.meta.port }}"
    - name: META_PROTOCOL
      value: "{{ .Values.meta.protocol }}"
    - name: META_BOOTSTRAP_PARAMS
      value: "migrate=false"
      
    #
    # -- Installer-provisioned services --
    #
    - name: GESTALT_CLI_DATA
      value: "{{ .Values.installer.gestaltCliData }}"
