apiVersion: v1
kind: Service
metadata:
  name: gestalt-meta
  labels:
    gestalt-app: meta
    gestalt-deployment: {{ .Values.deploymentLabel }}
spec:
  type: LoadBalancer
  selector:
    gestalt-app: meta
  ports:
    - name: http-api
      port: {{ .Values.Meta.Port }}
      targetPort: service-api
