apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-rabbit
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: rabbit
    spec:
      containers:
      - name: gestalt-rabbit
        image: "galacticfog/rabbit:{{ .Values.Common.ReleaseTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.Rabbit.Port}}
          name: service-api
        - containerPort: {{.Values.Rabbit.HttpPort}}
          name: http-api
