apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-rabbit
  labels:
    gestalt-app: rabbit
    gestalt-deployment: {{ .Values.deploymentLabel }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: rabbit
        gestalt-deployment: {{ .Values.deploymentLabel }}
    spec:
      containers:
      - name: gestalt-rabbit
        image: "galacticfog/rabbit:{{ .Values.Common.ReleaseTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.Rabbit.Port}}
          name: service-api
        - containerPort: {{.Values.Rabbit.HttpPort}}
          name: http-api
