apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-rabbit
  labels:
    gestalt-app: rabbit
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: rabbit
    spec:
      containers:
      - name: gestalt-rabbit
        image: "{{ .Values.rabbit.image }}"
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        ports:
        - containerPort: {{.Values.rabbit.port}}
          name: service-api
        - containerPort: {{.Values.rabbit.httpPort}}
          name: http-api
