apiVersion: v1
kind: Service
metadata:
  name: gestalt-security
  labels:
    gestalt-app: security
    gestalt-deployment: {{ .Values.deploymentLabel }}
spec:
  type: LoadBalancer
  selector:
    gestalt-app: security
  ports:
    - name: service-api
      port: {{ .Values.Security.Port }}
      targetPort: service-api
