apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-security
  labels:
    gestalt-app: security
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: security
    spec:
      containers:
      - name: gestalt-security
        image: "{{ .Values.security.image }}"
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        ports:
        - containerPort: 9000
          name: service-api
        env:
        - name: DATABASE_HOSTNAME
          value: "{{ .Values.db.hostname }}"
        - name: DATABASE_PORT
          value: "{{ .Values.db.port }}"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: gestalt-secrets
              key: db-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gestalt-secrets
              key: db-password
        - name: DATABASE_NAME
          value: "gestalt-security"
        - name: OAUTH_RATE_LIMITING_AMOUNT
          value: "100"
        - name: OAUTH_RATE_LIMITING_PERIOD
          value: "1"
