apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-security
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: security
    spec:
      containers:
      - name: gestalt-security
        image: "galacticfog/gestalt-security:{{ .Values.Common.ReleaseTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: service-api
        env:
        - name: DATABASE_HOSTNAME
          value: "{{ .Values.DB.Hostname }}"
        - name: DATABASE_PORT
          value: "{{ .Values.DB.Port }}"
        - name: DATABASE_USERNAME
          value: "{{ .Values.DB.Username }}"
        - name: DATABASE_PASSWORD
          value: "{{ .Values.DB.Password }}"
        - name: DATABASE_NAME
          value: "gestalt-security"
        - name: OAUTH_RATE_LIMITING_AMOUNT
          value: "100"
        - name: OAUTH_RATE_LIMITING_PERIOD
          value: "1"
