apiVersion: v1
kind: Service
metadata:
  name: gestalt-ui
  labels:
    gestalt-app: ui
    gestalt-deployment: {{ .Values.deploymentLabel }}
spec:
  type: LoadBalancer
  selector:
    gestalt-app: ui
  ports:
    - name: http
      port: 80
      nodePort: 32680
