apiVersion: v1
kind: Service
metadata:
  name: gestalt-ui
  labels:
    gestalt-app: ui
spec:
  type: {{ .Values.ui.exposedServiceType }}
  selector:
    gestalt-app: ui
  ports:
    - name: http
      port: 80
