apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-ui
  labels:
    gestalt-app: ui
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        gestalt-app: ui
    spec:
      containers:
      - name: gestalt-ui
        image: "{{ .Values.ui.image }}"
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: META_API_URL
          value: "{{ .Values.meta.protocol }}://{{ .Values.meta.hostname }}:{{ .Values.meta.port }}"
        - name: SEC_API_URL
          value: "{{ .Values.security.protocol }}://{{ .Values.security.hostname }}:{{ .Values.security.port }}"
