name: gestalt
home: http://www.galacticfog.com
version: 1.0.0
description: Cloud-native container management platform and serverless engine
# icon: https://raw.githubusercontent.com/galacticfog/gestalt/master/logos/gestalt-horizontal-color.png
sources:
  - https://github.com/GalacticFog
maintainers:
  - name: Gestalt Team @ Galactic Fog
    email: eric@galacticfog.com
